#!/usr/bin/env bash
#
# This script locks and removes the root account's password (if one is set). This
# prevents users from successfully logging into the root account via su. Note that it
# doesn't not prevent users from becoming root via methods such as sudo su.
#
# Version: v1.0.3
# License: MIT License
#          Copyright (c) 2020-2024 Hunter T. (StrangeRanger)
#
########################################################################################
####[ Variables ]#######################################################################


red="$(printf '\033[1;31m')"
nc="$(printf '\033[0m')"


####[ Prepping ]########################################################################


## Check if the script was executed with root privilege.
if [[ $EUID = 0 ]]; then
    echo "${red}Do NOT run this script as root or with root privilege${nc}" >&2
    echo -e "\nExiting..."
    exit 1
fi

####[ Main ]############################################################################

read -rp "We will now disable the root account. Press [Enter] to continue."
dsenableroot -d
